export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const CREATE_TASK_SUCCESS = "CREATE_TASKS_SUCCESS";

export const LOAD_ENTITIES_SUCCESS = "LOAD_ENTITIES_SUCCESS";
export const UPDATE_ENTITY_SUCCESS = "UPDATE_ENTITIES_SUCCESS";
export const CREATE_ENTITY_SUCCESS = "CREATE_ENTITIES_SUCCESS";
